project:
  type: website

website:
  title: "Christian Stratton"
  navbar:
    search: true
    left:
      # - text: Home
      #   href: index.qmd
      - text: Publications
        href: publications.qmd
      - text: Presentations
        href: presentations.qmd
      - text: CV
        href: cv.qmd
    tools:
      - icon: github
        href: https://github.com/StrattonCh
      - icon: envelope-at
        href: mailto:3strattonc@gmail.com

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto


# quarto render
# quarto publish gh-pages