---
title: "cv"
format: 
  pdf:
    template: cvtemplate.tex
editor: visual
---
<!-- header -->
\vspace*{-40pt}
\vspace*{-10pt}
\begin{center}
{\Huge \scshape {Christian A. Stratton}} \\
\faMapMarker \ 102 Branegan Court, Apt A. Bozeman, MT, 59715 \\
\faEnvelope \ christianstratton@montana.edu \\ 
\faPhone \ (406) 261-9426 \\ 
\end{center}
\vspace*{2mm}

<!-- summary -->
\header{Summary - \textcolor{red}{needs updating}}
\vspace*{2mm}

Candidate for a Ph.D. in Statistics with consulting, research and teaching experience. Strong analytical skills including model-based ordination, multi-scale occupancy modeling, mixed modeling, and Bayesian data analysis. Advanced programmer and problem solver with extensive experience with ecological data types. Skillful at collaborating and communicating complex concepts both verbally and in writing.

<!-- education -->
\header{Education}
\vspace*{2mm}

\textbf{Montana State University} \hfill Bozeman, MT

Bachelor of Science with Honors in Mathematics (focus: Statistics) \hfill December 2016

\vspace{2mm}

\textbf{Montana State University} \hfill Bozeman, MT

Master of Science in Statistics \hfill May 2018  

\vspace{2mm}

\textbf{Montana State University}\hfill Bozeman, MT

Doctor of Philosophy in Statistics \hfill  May 2022

Dissertation: \textit{Bayesian Hierarchical Latent Variable Models for Ecological Data Types}

Advisors: Dr. Andrew Hoegh and Dr. Jennifer Green  

\vspace{2mm}

<!-- peer-review publications -->

\header{Peer-reviewed Journal Articles}
\vspace*{2mm}

\subheader{In Review}
\vspace*{2mm}

\textbf{Stratton, C.}, A. Hoegh, T.J. Rodhouse, J.L. Green, K.M. Banner, and K.M. Irvine.  Clustering and unconstrained ordination with Dirichlet process mixture models. In review in \textit{Methods in Ecology and Evolution}.
\vspace*{2mm}

\textbf{Stratton, C.}, K.M Irvine, K.M. Banner, E.S. Almberg, D. Bachen, and K. Smucker. Joint spatial modeling bridges the gap between disparate disease surveillance and population monitoring efforts informing conservation of at-risk bat species. In review in the \textit{Journal of Agricultural, Biological, and Environmental Statistics}.
\vspace*{2mm}

Oram, J., K.M. Banner, \textbf{C. Stratton}, and K.M. Irvine. Verifying species classification labels using stratified-by-species sampling reduces cost of long-term acoustic monitoring. In review in \textit{Methods in Ecology and Evolution}. 
\vspace*{2mm}

Retel, C., A.J. Strien, K.M. Irvine, and \textbf{C. Stratton}. Trends in plant cover derived from vegetation-plot data using ordinal zero-augmented beta regression. In review in the \textit{Journal of Vegetation Science}. 
\vspace*{2mm}

\subheader{Accepted}
\vspace*{2mm}

\textbf{Stratton, C.}, K.M. Irvine, K.M. Banner, W.J. Wright, C. Lausen, J. Rae. 2022. [Coupling validation effort with *in situ* bioacoustic data improves estimating relative activity and occupancy for multiple species with cross-species misclassifications.](https://doi.org/10.1111/2041-210X.13831) \textit{Methods in Ecology and Evolution}, 13(6), p. 1288 -- 1303.
\vspace*{2mm}

\textbf{Stratton, C.}, J.L. Green, and A. Hoegh. 2021. [Not just normal: Exploring power with Shiny apps.](https://doi.org/10.5070/T513146468) \textit{Technology Innovations in Statistics Education}, 13(1), p. 1 -- 37.
\vspace*{2mm}

\textbf{Stratton, C.}, A.J. Sepulveda, and A. Hoegh. 2020. [`msocc:` Fit and analyze computationally efficient multi-scale occupancy models in `R`.](https://doi.org/10.1111/2041-210X.13442) \textit{Methods in Ecology and Evolution}, 11(9), p. 1113 -- 1120.
\vspace*{2mm}

Hoegh, A., K. Flagg, and \textbf{C. Stratton}. 2018. Contributed comment on Article by Bradley, Holan, and Wikle [Invited commentary on ``Computationally efficient multivariate spatio-temporal models for high-dimensional count-valued data" by Jonathan R. Bradley, Scott H. Holan, and Christopher K. Wikle.](https://eds.p.ebscohost.com/abstract?site=eds&scope=site&jrnl=19360975&AN=138950462&h=fupOc1pyeH8dv67mdPoRzhYvo96LS%2bzCYNHIjAcMPojnVBydkua%2fXFU6RanU78MDh8WNMlzPVI%2fBxvaUiWvg%2bw%3d%3d&crl=c&resultLocal=ErrCrlNoResults&resultNs=Ehost&crlhashurl=login.aspx%3fdirect%3dtrue%26profile%3dehost%26scope%3dsite%26authtype%3dcrawler%26jrnl%3d19360975%26AN%3d138950462) \textit{Bayesian Data Analysis}, 13(1), p. 253 -- 310.
\vspace*{2mm}

Irvine, K.M., K.M. Banner, \textbf{C. Stratton}, W.M. Ford, and B.E. Reichert. 2022. [Statistical assessment on determining local presence of rare bat species.](https://doi.org/10.1002/ecs2.4142) \textit{Ecosphere}, 13(6), p. e4142.
\vspace*{2mm}

Khalighifar, A., B.S. Gotthold, E. Adams, J. Barnett, L.O. Beard, E.R. Britzke, P.A. Burger, K. Chase, Z. Cordes, P.M. Cryan, E. Ferrall, C.T. Fill, S.E. Gibson, G.S. Haulton, K.M. Irvine, L.S. Katz, W.L. Kendall, C.A. Long, O.M. Aodha, T. McBurney, S. McCarthy, M.W. McKown, J. O'Keefe, L.D. Patterson, K.A. Pitcher, M. Rustand, J.L. Segers, K. Seppanen, J.L. Simers, \textbf{C. Stratton}, B.R. Straw, T.J. Weller, and B.E. Reichert. 2022. [\textit{NABat ML}: Utilizing deep learning to enable crowdsourced development of automated, scalable solutions for documenting North American bat populations.](https://doi.org/10.1111/1365-2664.14280) \textit{Journal of Applied Ecology}, 56(11), p. 2849 -- 2862.
\vspace*{2mm}

Sepulveda, A.J., A. Hoegh, J.A. Gage, S.L Caldwell-Eldridge, J.M. Birch, \textbf{C. Stratton}, P.R. Hutchins, E.P. Barnhart. 2021. [Integrating environmental DNA results with diverse data sets to improve biosurveillance of river health.](https://doi.org/10.3389/fevo.2021.620715) \textit{Frontiers in Ecology and Evolution}, 9, p. 1 -- 13.
\vspace*{2mm}

Sepulveda, A. J., C. Schmidt, J. Amberg, P. Hutchins, \textbf{C. Stratton}, C. Mebane, M. B. Laramie, and D. S. Pilliod. 2019. [Adding invasive species biosurveillance to the U.S. Geological Survey streamgage network.](https://doi.org/10.1002/ecs2.2843) \textit{Ecosphere}, 10(8), p. 1 -- 17.
\vspace*{2mm}

<!-- peer-review tech reports -->

\header{Peer-reviewed Technical Reports}
\vspace*{2mm}

\textcolor{red}{Add data release for WNS vignette.}
\vspace*{2mm}

\textbf{Stratton, C.}, B.R. Straw, J.H. Cox, K.M. Irvine, F.C. Tousley, and B.E. Reichert. 2023. [Attributed North American Grid-Based Offshore Sampling Frames: U.S. Geological Survey data release.](https://doi.org/10.5066/P9H8NEOY)
\vspace*{2mm}

\textbf{Stratton, C.}, K.M. Irvine. 2022. Summertime analysis statistical report for Little Brown, Northern Long-eared, and Tricolored bat species status assessment. Chapter B in Straw, B.R, J. A. Martin, J.D Reichard, and B.E Reichert, editors. [Analytical assessments in support of the U.S. Fish and Wildlife Service 3-Bat species status assessment. Cooperator report prepared in cooperation with the U.S. Geological Survey, United States Fish and Wildlife Service and Bat Conservation International.](https://doi.org/10.7944/P9B4RWEU)
\vspace*{2mm}

\textbf{Stratton, C.}, A. Hoegh, K. M. Irvine, K. Legg, K. McCloskey, E. Shanahan, M. Tercek, and D. Thoma. 2019. [Assessing spatial and temporal patterns in sagebrush steppe vegetation communities, 2012-2018: Grand Teton National Park.](https://irma.nps.gov/DataStore/DownloadFile/631136) Natural Resource Report NPS/GRYN/NRR-2019/2020. National Park Service, Fort Collins, Colorado.
\vspace*{2mm}

Irvine, K.M., and \textbf{C. Stratton}. 2021. [Rangewide summertime model predictions for three bat species (\textit{Myotis lucifigus}, \textit{Myotis septentrionalis}, and \textit{Perimyotis subflavus}) from acoustic and mist net data 2010 to 2019: US Geological Survey data release.](https://doi.org/10.5066/P9XZ8D6N.)
\vspace*{2mm}

Udell, B.J., B.R. Straw, T.L. Cheng, K. Enns, W.F. Frick, B. Gotthold, K.M. Irvine, C. Lausen, S. Loeb, J.D. Reichard, T.J. Rodhouse, D. Smith, \textbf{C. Stratton}, W.E. Thogmartin, and B.E. Reichert. 2022. [Status and trends of North American bats: Summer occupancy analysis 2010-2019.](https://doi.org/10.5066/P92JGACB) U.S. Fish and Wildlife Service.
\vspace*{2mm}

Wessel, S.A., L. Jones, E. Kramer, \textbf{C. Stratton}, L. Shoemaker, and D. Laughlin. 2020. [Predictability and stability of sagebrush-steppe restoration in a changing climate.](https://journals.uwyo.edu/index.php/uwnpsrc/article/view/6791/6301) National Park Service Annual Report Vol. 43. 
\vspace*{2mm}

<!-- presentations -->

\header{Presentations}
\vspace*{2mm}

\textbf{Stratton, C.}, K.M. Irvine, K.M. Banner, E. Almberg, D. Bachen, and K. Smucker. \textit{Joint spatial modeling of ecological response and disease processes improves estimator precision.} 2023. Talk given at the Joint Statistical Meetings. Toronto, Ontario, Canada.
\vspace*{2mm}

\textbf{Stratton, C.}, K.M. Irvine, K.M. Banner, E. Almberg, D. Bachen, and K. Smucker. \textit{A statistical framework for integrating White-nose syndrome surveillance data and acoustic population monitoring data.} 2023. Talk given to the U.S. Geological Survey Disease Coordination Group. Virtual. 
\vspace*{2mm}

\textbf{Stratton, C.}, K.M. Irvine, K.M. Banner, E. Almberg, D. Bachen, and K. Smucker. \textit{Leveraging WNS surveillance and NABat data improves estimation of disease spread and bat activity.} 2023. Poster presented at the Whitenose Syndrome National Meeting. Palm Springs, California, USA.
\vspace*{2mm}

\textbf{Stratton, C.}, K.M. Irvine, E. Almberg, K. Smucker, and J. Gude. \textit{Joint spatial modeling of relative activity and disease processes.} 2022. Poster presented at the ENVR 2022 Workshop: Environmental and Ecological Statistical Research and Applications with Societal Impacts. Provo, Utah, USA.
\vspace*{2mm}

\textbf{Stratton, C.}, K.M. Irvine, E. Almberg, K. Smucker, and J. Gude. \textit{Bats \& Stats: Assessing Impacts of White-nose Syndrome on Western Bat Species.} 2022. Talk given at the Northern Rocky Mountain Science Center. Bozeman, Montana, USA. 
\vspace*{2mm}

\textbf{Stratton, C.}, A. Hoegh, K.M. Irvine, K.M. Banner. 2021. \textit{Clustering and ordination with Dirichlet process mixture models.} Invited talk given at the Joint Statistical Meetings. Virtual.
\vspace*{2mm}

\textbf{Stratton, C.}, J.L. Green. 2021. \textit{Beyond normal: Understanding power through {\sf R} Shiny.} Poster presented at the United States Conference on Teaching Statistics. Virtual.
\vspace*{2mm}

\textbf{Stratton, C.}, A. Hoegh, and J.L. Green. 2018. \textit{Predicting pitch type: A case study in Bayesian hierarchical multinomial regression.} Invited talk given at the Joint Statistical Meetings. Vancouver, Canada.
\vspace*{2mm}

\textbf{Stratton, C.}, A. Hoegh, and J.L. Green. 2018. \textit{Unraveling Kershaw's dominance.} Poster presented at The Cascadia Symposium on Statistics in Sports. Vancouver, Canada. 
\vspace*{2mm}

\textbf{Stratton, C.} and J.L. Green. 2018. \textit{The power of technology: A Shiny applet assisted approach to teaching statistical power.} Electronic poster presented at the Electronic Conference on Teaching Statistics. Virtual.
\vspace*{2mm}

<!-- experience -->

\header{Experience}
\vspace*{2mm}

\textbf{Montana State University} \hfill Bozeman, MT

\textit{Post-doctoral researcher} \hfill July 2022 | Present

Advisors: Dr. Kathryn Irvine (USGS) and Dr. Katharine Banner (MSU)
\vspace{-1mm}
\begin{itemize} \itemsep 1pt
	\item 
\end{itemize}

\textbf{U.S. Geological Survey} \hfill Bozeman, MT

\textit{Student contractor} \hfill August 2020 | July 2022

\vspace{-1mm}
\begin{itemize} \itemsep 1pt
	\item Authored multiple papers and statistical reports
	\item Consulted on multiple analyses
	\item Communicated with domain experts and scientists
\end{itemize}

\textbf{Montana State University} \hfill Bozeman, MT

\textit{Math Learning Center Supervisor} \hfill June 2019 | December 2019

\vspace{-1mm}
\begin{itemize} \itemsep 1pt
	\item Supervised graduate and undergraduate tutors
	\item Successfully coordinated monthly meetings
	\item Proposed and implemented logistical improvements including novel tutoring practices
	\item Coached new tutors on how to effectively communicate mathematics
\end{itemize}

\textbf{Montana State University} \hfill Bozeman, MT

\textit{Graduate Research Assistant} \hfill January 2019 | August 2020

\vspace{-1mm}
\begin{itemize} \itemsep 1pt
	\item Resolved a wide scope of ecological problems using various techniques
	\item Collaborated and communicated with domain experts in ecology and land-resource management
	\item Developed models and tools to aid collaborators
	\item Authored multiple papers, web applications, and R packages
\end{itemize}

\textbf{Montana State University} \hfill Bozeman, MT

\textit{Statistical Consultant} \hfill August 2017 | May 2018

\vspace{-1mm}
\begin{itemize} \itemsep 1pt
	\item Communicated with clients
	\item Identified solutions to a wide scope of problems
	\item Successfully collaborated across departments to resolve problems
\end{itemize}

\textbf{Montana State University} \hfill Bozeman, MT

\textit{Graduate Teaching Assistant} \hfill January 2017 | December 2018

\vspace{-1mm}
\begin{itemize} \itemsep 1pt
	\item Taught over 80 students introductory statistics
	\item Planned and prepared course materials including test questions and written assignments
	\item Coached students in a collaborative learning environment
\end{itemize}

\textbf{Montana State University} \hfill Bozeman, MT

\textit{Math Learning Center Tutor} \hfill August 2014 | December 2016 

\vspace{-1mm}
\begin{itemize} \itemsep 1pt
	\item 
\end{itemize}

<!-- teaching experience -->
\header{Teaching Experience}
\vspace*{2mm}

216, 217, 411, guest lecturer 408, guest lecturer 402/502

<!-- service -->
\header{Service}

STEAM day, MT ASA, DataFest, BEES

<!-- coursework -->
\header{Coursework}
\vspace*{2mm}


<!-- awards -->
\header{Awards}
\vspace*{2mm}
\textbf{Three Minute Thesis Competition Finalist} \hfill Bozeman, MT

Finalist for the Three Minute Thesis competition \hfill February 2020

\vspace*{2mm}

\textbf{Dr. William A. Stannard Award for Excellence} \hfill Bozeman, MT

Recognition of outstanding graduate student teaching \hfill May 2018

\vspace*{2mm}

\textbf{Outstanding Graduate Student Award} \hfill Bozeman, MT

Recognition of superior academic achievement among graduate students \hfill May 2017

\vspace*{2mm}

\textbf{John L. Magaret Math/Science Scholarship} \hfill Bozeman, MT

Recipient of scholarship for outstanding academic achievement \hfill January 2017

\vspace*{2mm}

\textbf{Milton-Chauner Math Scholarship} \hfill Bozeman, MT

Recipient of scholarship for outstanding academic achievement \hfill August 2016

\vspace*{2mm}

\textbf{Outstanding Undergraduate Student Award} \hfill Bozeman, MT

Recognition of superior academic achievement among undergraduate students \hfill May 2016

\vspace*{2mm}

\textbf{Outstanding Scholar Award} \hfill Bozeman, MT

Recognition of superior academic performance \hfill May 2016

\vspace*{2mm}

\textbf{Montana State University System Award} \hfill Bozeman, MT

Scholarship for outstanding academic performance \hfill December 2015

\vspace*{2mm}

\textbf{Phi Kappa Phi} \hfill Bozeman, MT

Member of Phi Kappa Phi, a national multi-disciplinary honor society \hfill March 2015

\vspace*{2mm}

\textbf{Pi Mu Epsilon} \hfill Bozeman, MT

Member of Pi Mu Epsilon, a national mathematics honor society \hfill December 2014

\vspace*{2mm}

