---
title: "Statement - teaching"
format: 
  pdf:
    template: cvtemplate.tex
editor: source
---
<!-- advice: https://crlt.umich.edu/sites/default/files/resource_files/CRLT_no23.pdf -->

\begin{flushright}
Christian Stratton

\href{mailto:christianstratton@montana.edu}{christianstratton@montana.edu}

(406) 261-9426
\end{flushright}

\begin{center}
\textbf{Statement on teaching philosophy} 
\end{center}

As I reflect on some of the most memorable and impactful courses from my time as a student, a common theme emerges: they were all taught by outstanding educators who were excited about statistics and intentionally engaged the students in their classrooms. In each of these classes, the instructors made concerted efforts to create an environment where the students actively participated in learning rather than simply recording information. My teaching philosophy reflects this core tenet and has been further shaped by a wide array of teaching experiences to a diverse collection of students. As an undergraduate student, I worked in the Math and Stat Learning Center and tutored a wide variety of courses, from College Algebra to Calculus III and Linear Algebra to Intermediate Statistical Concepts. During this time, I also served as a teaching assistant for Introduction to Statistics, where I facilitated labs. As a graduate student, I had the opportunity to be lead instructor of the introductory and intermediate statistics courses at Montana State, where my responsibilities included creating lecture materials, holding office hours


\vspace*{2mm}



\vspace*{2mm}

\begin{itemize}
\item paragraph on engaging students (active learning and technology)
\item paragraph on supervising MLC, teaching wide variety of students and classes
\item paragraph on teaching 216/217 with a flipped classroom, stat 411 labs with flipped classroom
\item paragraph on designing tool for teaching power, and visualizations in 408
\item school-centric paragraph, list some courses that I would like to teach, some that I would like to create 
\end{itemize}


<!-- I still vividly remember sitting down for my first day of introductory statistics with Dr. Katharine Banner in the fall of 2015. As we all wrestled with the installation of `R`, `R` Markdown, and MikTeX, Dr. Banner shared visualizations created in `R` from various projects during graduate school. Her excitement was palpable as she described the power of statistics to provide data-driven solutions to real-world problems. I recall spending the rest of my evening with the `cars` data set and StackOverflow, trying to figure out how to overlay a density plot on a histogram. -->

<!-- \vspace*{2mm} -->

<!-- A year later, I found myself enrolled in probability theory with Dr. Jennifer Green, thumbing through the course calendar before class, intimidated by terms like "Jacobian transformations" and "moment-generating functions." My anxiety was immediately alleviated as the ice-breaker on the first day of class ignited a 30-minute discussion about our backgrounds, expectations, and the power of statistics to change the way people think about the world. Each of the following classes began with a prompt first discussed in small groups, then again shared as a class. This technique left me feeling excited for class despite my trepidation prior to the start of the semester. For the remainder of my time in school, Dr. Green remained remarkably approachable, always happy to talk about effective teaching strategies, or other statistical novelties, such as how the hypergeometric distribution may be used in forensic glass comparison. -->

<!-- \vspace*{2mm} -->

<!-- Two years later in the fall of 2017, I enrolled in Bayesian data analysis with Dr. Andrew Hoegh. Frequently throughout the semester, Dr. Hoegh flipped the classroom, encouraging us to work in groups to derive posterior distributions and construct MCMC samplers. During this time, Dr. Hoegh would visit with each group and field questions, at times posing new questions for the group to ponder. Through this process, I developed a deep curiosity for Bayesian statistics, which motivated me to visit Dr. Hoegh's office hours frequently. During these visits, we had lengthy conversations about the philosophy of Bayesian statistics, practical applications, and the nuts and bolts of Bayesian computation. These conversations are particularly memorable, as Dr. Hoegh would tirelessly entertain my curiosities, often answering questions with questions and encouraging me to dive deeper into literature and scholarship. -->







