---
title: "Cover letter"
format:
  pdf:
    template: cvtemplate.tex
editor: source
---

\begin{flushright}
Christian Stratton \\
2-214 Wilson Hall \\ 
P.O. Box 172400 \\
Bozeman, MT 59717-2400 \\
\href{mailto:christianstratton@montana.edu}{christianstratton@montana.edu} \\
\href{https://strattonch.github.io/christianstratton/}{https://strattonch.github.io/christianstratton/}\\
(406) 261-9426
\end{flushright}

\vspace*{2mm}

[**DATE**]

\vspace*{2mm}

[**COMMITTEE CHAIR**]

Search Committee 

[**DEPARTMENT**] 

[**SCHOOL**] 

[**ADDRESS**] 

\vspace*{2mm}

Dear Dr. [**COMMITTEE CHAIR**],

\vspace*{2mm}

I write to apply for the [**JOB TITLE**] opening at [**SCHOOL**]. I am a post-doctoral researcher in statistics at Montana State University, co-advised by Dr. Kathryn Irvine at the U.S. Geological Survey and Dr. Katharine Banner at Montana State University. My research during my post-doctoral appointment and graduate program primarily focused on development of statistical methodology for the environmental and ecological sciences, but I also have interest and experience in statistics education, sports analytics, and [**INCLUDE AREAS HIGHLIGHTED ON LISTING**]. I am attracted to [**REASON FOR INTEREST IN SCHOOL**]. My contributions to the species distribution modeling literature, dedication to collaborative research, and history of excellence in teaching have prepared me well to research and teach at [**SCHOOL**].

\vspace*{2mm}

My research on species distribution modeling and wildlife disease modeling aligns well with your department's commitment to development of novel statistical methodology to address pressing scientific questions. As a post-doctoral researcher, I am working with multiple interdisciplinary scientists at the North American Bat Monitoring Program (NABat), a multi-agency, multi-discipline, collaborative monitoring program that aims to assess the status and trend of bat populations in North America. As one of two statisticians on the team of interdisciplinary scientists, I am developing statistical methodology to address pressing conservation concerns and communicating and collaborating with domain experts in data science, ecology, and resource management. My recent work with the NABat program concerns the assessment of the impact of White-nose syndrome (WNS), a disease caused by an invasive fungus on bats in North America. This assessment requires development of a spatial modeling framework that jointly models acoustic bat activity data and WNS surveillance data. A manuscript detailing this modeling framework is currently in review in the \emph{Journal of Agricultural, Biological, and Environmental Statistics} and will be provided upon request.

\vspace*{2mm}

My experience collaborating with domain scientists from multiple disciplines and government agencies positions me well to work with the diverse faculty at [**SCHOOL**] and forge new collaborative relationships on behalf of the university. For example during my graduate program, I worked with United State Geological Survey (USGS) scientists to develop an R package, `msocc`, that leverages data augmentation strategies to fit fully Bayesian computationally efficient multi-scale occupancy models for environmental DNA applications. Following the `msocc` work, I collaborated with National Park Service scientists from Craters of the Moon National Monument and Preserve to develop a hierarchical ordination model that incorporates Bayesian nonparametric techniques to estimate the number of distinct sagebrush vegetation communities present in the park. Finally, during my student contractor work with the USGS, I investigated the influence of validation data and prior specification on multi-species, false-positive occupancy modeling frameworks. These collaborations have led to multiple publications in \emph{Methods in Ecology and Evolution}. In addition to these three projects, I have worked collaboratively with other scientists in the environmental and ecological sciences, leading to four additional publications. I look forward to bringing these active collaborative relationships to [**SCHOOL**], and leveraging them to provide funding and research opportunities for students. 

\vspace*{2mm}

In the next three-to-five years, I will continue researching development of statistical methodology for the environmental and ecological sciences, focusing on species distribution modeling, Bayesian computation, and data integration. In addition to my active projects concerning species distribution modeling and data integration, I am currently working to address the scalability of the joint spatial model discussed above by exploring data augmentation strategies to implement efficient MCMC sampling techniques and computationally efficient alternatives to the Gaussian process implemented in the model. My continued work on state-of-the-art statistical methodology in the environmental and ecological sciences will add to the already diverse research profile of your department, providing more research opportunities for students and expanding the reach of [**SCHOOL**].

\vspace*{2mm}

In addition to my research presence, I am a rigorous, dedicated, and successful teacher, with multiple semesters of lead instructor experience teaching the introductory and intermediate statistics courses at Montana State University. Additionally, I have provided lectures and facilitated guided activities for various upper-level statistics courses, including courses on mathematical statistics, computational statistics, and linear models. My teaching philosophy is designed to build an inclusive environment where students are actively engaged in the learning process. I do this by implementing active learning strategies, building rapport with my students, and acting on student feedback. Student evaluations have spoken favorably of my teaching practices, and the Department of Mathematical Sciences has recognized my teaching ability with the Dr. William A. Stannard Award for Teaching Excellence, an award given to one graduate student each year in recognition of outstanding teaching achievements. 

\vspace*{2mm}

Outside of the classroom, I am committed to excellence in teaching by developing new teaching materials and practices that leverage modern resources to provide statistics instruction. For example, I developed an `R` Shiny web application to facilitate teaching statistical power to undergraduate and graduate-level statistics students. The web application was designed to help students visualize how a statistics’ power function is based on the sampling distribution of that statistic under multiple assumptions. The web application also provided additional knobs allowing students to investigate the influence of sample size, significance level, and the alternative hypothesis on the power function. During my graduate program, I implemented this web application alongside a guided activity to teach power at the undergraduate and graduate-level. The web application has since been used multiple times to teach power at Montana State University and Michigan State University. A description of the web application and its implementation is published in \emph{Technology Innovations in Statistics Education}. Together, my teaching and research experiences coupled with broad coursework during my graduate program, position me to teach a variety of courses and provide students at [**SCHOOL**] with a diverse collection of research opportunities. 

\vspace*{2mm}

Finally, I have engaged in multiple opportunities for service and provided mentoring to graduate students and members of the community at Montana State. I am the co-president of the Bozeman Environmental and Ecological Statistics group (BEES), a research group that focuses on introducing graduate students to statistical methodology for environmental and ecological statistics and provides mentoring and support to students working in the field of ecological statistics. I also currently serve as the chapter secretary and council of chapters representative for the Montana Chapter of the American Statistical Association. Beyond academic service, I volunteered for Montana State’s STEAM Day in the spring of 2023. STEAM Day is a one-day conference that includes hands-on workshops in science, technology, engineering, art, and math (STEAM) for middle school girls in grades six, seven, and eight across Montana. The event served as an opportunity to invite middle school girls from diverse backgrounds, including students from low-income areas and American Indian communities, to consider careers in STEAM fields. I look forward to continuing to engage in mentoring and service at [**SCHOOL**], and plan to explore additional ways to engage the local communities. 
\vspace*{2mm}

I am excited about the possibility of becoming your colleague, and I am available to meet with you for an interview at your convenience. You will receive letters of reference from Drs. Andrew Hoegh (\href{mailto:andrew.hoegh@montana.edu}{andrew.hoegh@montana.edu}), Kathryn Irvine (\href{mailto:kirvine@usgs.gov}{kirvine@usgs.gov}), Jennifer Green (\href{mailto:jg@msu.edu}{jg@msu.edu}), and Stacey Hancock (\href{mailto:stacey.hancock@montana.edu}{stacey.hancock@montana.edu}). For additional information, including links to published papers and updates on submitted papers, please visit my personal website at \href{https://strattonch.github.io/christianstratton/}{https://strattonch.github.io/christianstratton/}. If you need additional materials, including writing samples, teaching evaluations, or course syllabi, please do not hesitate to contact me. Thank you for your time and consideration of my application, and I look forward to hearing from you.

\vspace*{2mm}

Sincerely,

\vspace*{15mm}

Christian Stratton
