---
title: "Cover letter"
format:
  pdf:
    template: cvtemplate.tex
editor: source
---

\begin{flushright}
Christian Stratton \\
2-214 Wilson Hall \\ 
P.O. Box 172400 \\
Bozeman, MT 59717-2400 \\
\href{mailto:christianstratton@montana.edu}{christianstratton@montana.edu} \\
\href{https://strattonch.github.io/christianstratton/}{https://strattonch.github.io/christianstratton/}\\
(406) 261-9426
\end{flushright}

\vspace*{2mm}

[**DATE**]

\vspace*{2mm}

[**COMMITTEE CHAIR**]

Search Committee 

[**DEPARTMENT**] 

[**SCHOOL**] 

[**ADDRESS**] 

\vspace*{2mm}

Dear Dr. [**COMMITTEE CHAIR**],

\vspace*{2mm}

I am writing to apply for the [**JOB TITLE**] opening at [**SCHOOL**]. I am a post-doctoral researcher in statistics, co-advised by Dr. Kathryn Irvine at the U.S. Geological Survey and Dr. Katharine Banner at Montana State University. My research during my post-doctoral appointment and graduate program primarily focused on development of statistical methodology for the environmental and ecological sciences, but I also have interest and experience in statistics education, sports analytics, and [**INCLUDE AREAS HIGHLIGHTED ON LISTING**]. I am attracted to [**REASON FOR INTEREST IN SCHOOL**].

\vspace*{2mm}

My post-doctoral work has focused on development of novel statistical methodology for modeling of species distributions and wildlife diseases to support the North American Bat Monitoring Program (NABat). The NABat program is a multi-agency, multi-discipline, collaborative monitoring program that aims to assess the status and trend of bat populations in North America. As one of two statisticians on the team of interdisciplinary scientists, my role entails timely development of statistical methodology to address pressing conservation concerns and communicating and collaborating with domain experts in data science, ecology, and resource management. My recent work with the NABat program concerns the assessment of the impact of White-nose syndrome (WNS), a disease caused by an invasive fungus, on bats in North America. This assessment required development of a spatial modeling framework that jointly models acoustic bat activity data with WNS surveillance data. A manuscript detailing this modeling framework is currently in review in the \emph{Journal of Agricultural, Biological, and Environmental Statistics} and will be provided upon request.

\vspace*{2mm}

Prior to my post-doctoral appointment, I collaborated with scientists in the environmental and ecological sciences on a variety of projects. During my graduate program, I developed an `R` package, `msocc`, that leverages data augmentation strategies to fit fully Bayesian, computationally efficient multi-scale occupancy models for environmental DNA applications. Following the `msocc` work, I developed a hierarchical ordination model that incorporates Bayesian nonparametric techniques to estimate the number of distinct sagebrush vegetation communities in Craters of the Moon National Monument and Preserve. Finally, during my student contractor work with the U.S. Geological Survey, I investigated the influence of validation data and prior specification on multi-species, false-positive occupancy modeling frameworks. These projects have led to multiple publications in \emph{Methods in Ecology and Evolution}. Additionally, I have worked collaboratively with other scientists in the environmental and ecological sciences, leading to four additional publications. 

\vspace*{2mm}

In the next three-to-five years, I will continue developing statistical methodology for the environmental and ecological sciences. Specifically, I am interested in development of computationally efficient statistical methodology for the large spatial data sets that are often encountered in environmental applications. I am currently working to address the scalability of the joint spatial model discussed above by exploring data augmentation strategies to implement efficient MCMC sampling techniques. Additionally, I am interested in researching computationally efficient alternatives to the standard Gaussian process implemented in the model, including locally approximated and nearest neighbor Gaussian processes. 

\vspace*{2mm}

Beyond the joint spatial modeling framework and computational work, I am interested in techniques for data integration and data fusion and will continue to research these topics for the next three-to-five years. As the world becomes more data driven and access to citizen science data sources increases, the need for development of statistical methodology that accommodates multiple data sources also increases. I am currently developing a hierarchical modeling framework, motivated by a spatial point process, that can accommodate multiple different types of bat data sources; a manuscript detailing this methodology is currently in preparation. 

\vspace*{2mm}

In addition to research, teaching is a fundamental component of my academic life. During my graduate program, I developed an `R` Shiny web application to facilitate teaching statistical power to undergraduate and graduate level statistics students. The web application was designed to help students visualize how a statistics' power function is based on the sampling distribution of that statistic under multiple assumptions. During my graduate program, I implemented this web application alongside a guided activity to teach power at the undergraduate and graduate level. The web application has since been used multiple times to teach power at Montana State University and Michigan State University. A description of the web application and its implementation is published in \emph{Technology Innovations in Statistics Education}. 

\vspace*{2mm}

Besides the implementation of the web application in undergraduate and graduate level mathematical statistics courses, I have experience teaching a variety of courses at the undergraduate level to a diverse group of students. Prior to my work as a graduate research assistant and student contractor, I served as lead instructor for the introductory and intermediate statistics courses for multiple semesters. Additionally, during my post-doctoral appointment with the U.S. Geological Survey, I collaborated with domain experts from multiple science fields and disciplines. Through this experience, I gained valuable insight into the role of statisticians outside of academia. Together, my teaching and research experiences coupled with broad coursework during my graduate program, position me to teach a variety of courses and provide students with a unique perspective on opportunities for statisticians outside of academia. In particular, I would be comfortable teaching [**COURSES AT SCHOOL**] and contributing [**NEW COURSES**]. 

\vspace*{2mm}

Finally, I have rigorously sought opportunities for mentoring and service. During my post-doctoral appointment, I served as co-president of the Bozeman Environmental and Ecological Statistics group (BEES), a research group focused on introducing graduate students to statistical methodology for environmental and ecological statistics. During this time, I also served as the chapter secretary and council of chapters representative for the Montana Chapter of the American Statistical Association. Beyond academic service, I volunteered for Montana State's STEAM Day in the spring of 2023. STEAM Day is a one-day conference that includes hands-on workshops in science, technology, engineering, art, and math (STEAM) for middle school girls in grades six, seven, and eight across Montana. The event served as an opportunity to invite middle school girls from diverse backgrounds, including students from low-income areas and American Indian communities, to consider careers in STEAM fields.

\vspace*{2mm}

Attached to this letter are my *curriculum vitae*, research statement, teaching statement, and statement on diversity, equity, and inclusion. [**CHECK ALL THREE ARE REQUIRED**] Letters of reference will be provided by Dr. Andrew Hoegh (\href{mailto:andrew.hoegh@montana.edu}{andrew.hoegh@montana.edu}), Dr. Kathryn Irvine (\href{mailto:kirvine@usgs.gov}{kirvine@usgs.gov}), Dr. Jennifer Green (\href{mailto:jg@msu.edu}{jg@msu.edu}), and Dr. Stacey Hancock (\href{mailto:stacey.hancock@montana.edu}{stacey.hancock@montana.edu}). For additional details, including links to published papers and updates on submitted papers, please visit my personal website at \href{https://strattonch.github.io/christianstratton/}{https://strattonch.github.io/christianstratton/}. I am happy to provide additional materials upon request. Please contact me with any questions, I can be reached via email at \href{mailto:christianstratton@montana.edu}{christianstratton@montana.edu} or by phone at (406) 261-9426. Thank you for your consideration of these materials. 

\vspace*{2mm}

Sincerely,

\vspace*{15mm}

Christian Stratton
