
---
title: "Statement - DEI"
format:
  pdf:
    template: cvtemplate_aesthetic.tex
editor: source
---

\begin{flushright}
Christian Stratton

\href{mailto:christianstratton@montana.edu}{christianstratton@montana.edu}
\end{flushright}

\header{Statement on diversity, equity, and inclusion}
\vspace*{2mm}

Growing up in a low-income household and navigating the demands of working two jobs during my undergraduate years provided me with a firsthand account of some challenges people may face when pursuing higher education and careers in science, technology, engineering, and mathematics (STEM) fields. For example, I worked split shifts at Target for much of my undergraduate degree to stay afloat. Split shifts entailed working from 4:00 to 8:00 in the morning before catching a bus to attend class from 9:00 a.m. to 4:00 in the afternoon, then returning to close Target from 6:00 to 10:30 at night. During the 9:00 a.m. to 4:00 p.m. window during which I was on campus, I would spend two or three hours working in the Mathematics and Statistics Learning Center to bring in a little extra money. Some of my most vivid memories from college are a result of the hectic schedule I maintained to make ends meet: the smell of a pot of coffee set to brew at 2:00 a.m. as I prepared to continue studying for a Linear Algebra exam after finishing my Calculus III homework after work or the inquisitive looks I received from children on the public bus as I furiously scribbled down my homework on the way to class. 

\vspace*{2mm}

Despite this economic hardship during my childhood and undergraduate years, I have lived a privileged life. In addition to not facing the systemic barriers that individuals from under-represented communities face when pursuing careers in STEM fields, I always had access to an outstanding support system that helped me succeed during the difficult times in my education. My experience during my undergraduate degree has motivated me to be proactive about supporting and encouraging students facing hardships during their education and learn about other challenges students may face when pursuing a degree in a STEM field. While I am still learning about the many challenges individuals from the diverse populations of students at universities face, I am committed to taking action to support students facing difficulties during their time at university. 

\vspace*{2mm}

One challenge that students from under-represented communities have shared with me is accessibility. To help improve the accessibility of education in STEM fields, I served on multiple recruitment panels and met with numerous prospective students as a graduate student at Montana State University. This experience allowed me to engage with students from under-represented communities interested in careers in STEM fields and continue to learn about the challenges and obstacles individuals from these communities face. As a post-doctoral researcher, I continued these efforts by actively recruiting individuals from under-represented communities, including women and students from Ghana and Nigeria, to join a research group I co-led that explores statistical methodology for environmental applications. As a faculty member, I look forward to the opportunity to continue learning about the barriers in place for individuals from diverse populations of students at universities and to continue engaging with individuals from under-represented communities. As faculty, I hope to improve the accessibility of STEM education for individuals from under-represented communities by advising and mentoring students, providing funding opportunities through programs like NSF REUs, and continuing to focus on outreach to individuals from under-represented communities.

\vspace*{2mm}

During my time in graduate school and my post-doctoral appointment, I had the opportunity to learn more specifically about the obstacles facing women in STEM through the mentorship and guidance of female advisors. In particular, I learned about the barriers to entry in STEM fields for young women in public education systems. As a result, I am committed to improving the accessibility of careers in STEM fields for young women. Presenting a workshop at Montana State University's STEAM Day in the spring of 2023 exemplifies this commitment. STEAM Day is a one-day conference that includes hands-on workshops in science, technology, engineering, art, and math for middle school girls in grades six, seven, and eight across Montana. This event served as an opportunity to get middle school girls from diverse backgrounds, including students from low-income areas and American Indian communities, excited about careers in STEAM fields and encourage them to consider pathways to those careers.

\vspace*{2mm}

While participating in recruitment events and community workshops supports diversity, equity, and inclusion (DEI) outside the classroom, it is equally essential to support DEI inside the classroom. As the lead instructor of multiple introductory statistics courses while in graduate school, I intentionally supported students from diverse backgrounds. Examples of these efforts included: making homework and quiz accommodations for students balancing work and childcare with school, constructing diverse groups of students in active learning environments, and intentionally being inclusive with language and use of pronouns in class to create a safe environment for learning. While many of these individual efforts are seemingly small, in combination, they create a classroom in which individuals with diverse backgrounds and individuals from under-represented communities feel heard and can succeed.

\vspace{2mm}

As a faculty member, I will be committed to sustaining efforts to support DEI through continued service and in the classroom. I am excited to be a part of the support systems that enable students to succeed, just as Montana State faculty members were a part of my support system during my undergraduate degree. I look forward to the opportunity to continue to serve marginalized students and foster a diverse and equitable learning environment for students of all backgrounds, socio-economic status, race, identity, and religious affiliation. Through mentorship, recruitment, outreach, and advocacy, I am devoted to realizing lasting change and creating an environment where all students can be successful.



<!-- me not only to try to actively improve the accessibility of higher education to individuals from under-represented communities but also to learn about how I can better assist individuals from these communities with other challenges they may face. In particular, I am motivated to encourage students of all backgrounds to consider careers in STEM fields and actively engage with outreach programs to recruit students from under-represented communities.  -->


<!-- has given me a glimpse at some of the obstacles under-represented communities face when . While poverty is only one of the many challenges that individuals from under-represented communities may face, this experience has  -->
