---
title: "Statement - teaching revised"
format: 
  pdf:
    template: cvtemplate.tex
editor: source
---
<!-- advice: https://crlt.umich.edu/sites/default/files/resource_files/CRLT_no23.pdf -->

\begin{flushright}
Christian Stratton

\href{mailto:christianstratton@montana.edu}{christianstratton@montana.edu}
\end{flushright}

\begin{center}
\textbf{Teaching statement} 
\end{center}

When asked what I do for a living, I am frequently met with one of two responses, "Why would you want to do that?" or "That's cool; I took statistics in college and hated it." These responses characterize one of the main obstacles when teaching statistics: overcoming the stigma surrounding the discipline to engage the students. In the classroom, I deliberately construct my teaching philosophy to engage students in learning statistics by implementing active learning strategies, building rapport with students, and being attentive to student feedback.

\vspace*{2mm}

The first method I use to improve student engagement is the implementation of active learning strategies when teaching. Active learning is a term used to broadly describe teaching techniques that encourage students to learn by actively participating in learning rather than passively learning by listening to lectures. As the lead instructor of the introductory statistics course, I implemented active learning techniques by flipping the classroom and allowing students to work in small groups on guided activities. A typical 50-minute class period would begin with approximately 10 minutes of lecture, during which I would field questions and introduce the day's topic. Following that introduction, students would work on a guided activity in small groups for approximately 30 minutes as I moved around the room, visiting with groups individually and providing feedback. The class would conclude with a summary of the concepts discussed that day, and groups would have the opportunity to share what they learned. By flipping the classroom and having students work in small groups, students were engaged in learning statistics by necessity as their group mates relied upon the collective effort to learn the material. 

\vspace*{2mm}

As I became the lead instructor of the intermediate statistics course, I again implemented active learning strategies, though my methodology changed to accommodate the denser course material. Rather than allowing the class to work in groups on guided activities for the majority of the class period, I encouraged students to interact with each other for shorter periods throughout the class. One example of this type of active learning is the "think-pair-share" strategy, in which I would first pose a question and encourage students to think about it individually. Then, I would invite students to pair with nearby students and share their thoughts on the problem. This type of active learning was advantageous with the more advanced material for two reasons. First, it allowed me to guide the classroom discussion and provide direct instruction on complex topics. Second, it required that the students be active participants in classroom discussions of the material, thereby keeping them engaged in learning the material.

\vspace*{2mm}

When invited to guest lecture on statistical power for the undergraduate and graduate level mathematical statistics course, I again implemented active learning techniques to engage the students. To aid in our exploration of statistical power, I constructed an `R` Shiny web application that showed the implied distribution of the sample statistic under the null and alternative hypotheses for a wide variety of sample statistics and population distributions; a paper describing the web application and its implementation in class is published in [*Technology Innovations in Statistics Education*](https://doi.org/10.5070/T513146468). Both class periods were structured as a guided activity, allowing students to collaborate when interacting with the web application. This structure allowed the students to have hands-on experience with visualizations of power functions and derivations of those functions, ensuring they stayed engaged with learning the material. 

\vspace*{2mm}

I also improve engagement in the classroom by establishing rapport with students so that they feel comfortable asking questions and safe in the classroom. There are several effective ways to establish rapport with students, including building an inclusive classroom, being highly available, being knowledgeable and prepared for class, and being genuinely excited about the course material. A few examples of how I build an inclusive classroom include inviting students to specify their pronouns at the start of the semester, building diverse collections of students for group work, intentionally selecting data for use in class that do not alienate members of the class, and creating a space where students are comfortable asking questions. The other strategies for building rapport (availability, knowledge/preparation, excitement) are easily implemented by dedicating time to prepare before class. By building positive relationships with my students through these strategies, I have found that they are more receptive to feedback and generally more actively involved in classroom discussions. 

\vspace*{2mm}

Finally, I improve student engagement by frequently providing opportunities for students to give feedback on the course structure. In my experience, students are more active in class and receptive to feedback when I am receptive to feedback as the instructor. It is also important to acknowledge that not all students are the same and that there is no one-size-fits-all recipe for successful instruction. I frequently administer mid-semester evaluations to my students to adapt my teaching style to celebrate these differences. In these evaluations, I ask for feedback on the course structure and invite students to discuss parts of the class that are going well and parts that are not. This feedback allows me to adapt my teaching style during the semester to fit the needs of the students best. For example, during the Spring 2018 semester, feedback from the mid-semester evaluations was overwhelmingly against the fully flipped format. As a result, I switched my instruction style towards guided activities and think-pair-share opportunities. Student feedback was overwhelmingly supportive of the change mid-semester, leading to a more engaged classroom for the remainder of the semester. 

\vspace*{2mm}

During my time instructing in graduate school, students have been generally supportive and receptive to the techniques I have used to keep them engaged. At the end of this document, I provided a subset of student evaluations that speak directly to the efficacy of each technique described above. As I now transition from a post-doctoral researcher to a member of the faculty, I am excited by the opportunity to continue engaging students in the classroom. I am particularly excited for the chance to teach [**COURSES**]. Additionally, I would be happy to bring new courses to the department that are not listed on the online course registry, including: [**CHECK THESE AREN'T OFFERED/THERE IS A GRAD PROGRAM**] an undergraduate course in Bayesian statistics, a course in statistical methodology for environmental and ecological data, or a course on statistical programming and Markov Chain Monte Carlo techniques. If given the chance to become faculty at [**SCHOOL**], I look forward to contributing my teaching philosophy to the department and continuing to learn additional ways to be an effective professor.

\newpage

\textbf{Student evaluations in support of previous claims}

\emph{Comments on the flipped classroom format}

\begin{itemize}
\item I like the format, and how he taught the course. Was helpful and explained concepts clearly.
\item The format was good and Christian always seemed to know what he was talking about.
\item Group work made class fun and easy to ask for help.
\end{itemize}

\vspace*{2mm}

\emph{Comments on building rapport with availability, preparation, and knowledge and excitement about the material}

\begin{itemize}
\item Christian did a fantastic job of teaching this class. Mastery of course material was obvious, but he tried hard to stimulate one's interest for statistics. He was always available for assistance as well. Thanks for an awesome semester Christian, I really enjoyed this class, which is saying something because I don't really like math at all. You're a great teacher, keep it up.
\item Christian was a very kind and caring instructor. He was always available and willing to help everyone. Overall was great to work with. 
\item Professor seemed excited about stats so class was not boring. Professor always available when help was needed. Thanks!
\item Amazing teacher! He was very helpful + responsive to any questions we had throughout the semester. Christian is definitely an asset to the MSU stats department. 
\item Mr. Stratton is a great instructor. He is extremely helpful and clear in his presentations. He gives excellent and timely feedback and obviously puts a lot of effort into teaching this course. 
\item Great instructor for this course, he knew his material very well and knew how to teach it to us. He went out of his way to make reviews and prepare us for homework and tests. Really enjoyed learnings stats from him and would recommend him to my peers taking 216 in the future. Put in a lot of effort and was always helpful and understanding.
\item I appreciate your knowledge of the material and your willingness to help anytime.
\item Christian is a great teacher who clearly loves stats and is very concerned with students understanding of the material. 
\item I don't quite like stats, but I didn't hate coming to class because Christian was always excited to be there and made a difficult subject learnable by breaking it up into bite size pieces.
\item You genuinely cared about all of us and our understanding of statistics. You were enthusiastic (even when we weren't) and you went above and beyond for us even when you didn't have to. You have been the best TA I've had so far in my college career. It was a pleasure to learn statistics from you Christian!
\item Christan was one of the best teachers I've ever had. He was always available and actually was very helpful. He never made me feel stupid for asking a questions, which I've never had with a teacher before. He understood statistics very well and knew how to teach it to make sense. I would not have an A in stats if Christian wasn't my teacher.
\item Instructor was awesome, very educated in the subject. Knows how to adapt to your learning style to make it easier for you to understand the subject at hand. Would love to take another class taught by this instructor!
\end{itemize}

\emph{Comments on receptiveness to feedback from the Spring 2018 semester}

\begin{itemize}
\item The change in the way the class was taught at the end of the semester worked much better
\item Class went well. Breaking activities into group work and coming back together as a class was okay. Working as a class went better.
\item Didn't learn that much from the group work but when taught up front/asked for help things become more clear.
\item I thought that the course was very well known and explained well, I liked the flexibility you had with what teaching methods worked better. Overall, a good stats TA.
\end{itemize}

